# Generated by Django 4.2.18 on 2025-03-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='发表评论的用户昵称', max_length=255, verbose_name='用户昵称')),
                ('region', models.CharField(blank=True, help_text='用户所在地区（IP地址解析结果，可能为空）', max_length=255, null=True, verbose_name='用户地区')),
                ('comment_date', models.DateTimeField(help_text='评论发表的具体时间', verbose_name='评论时间')),
                ('content', models.TextField(help_text='用户发表的评论正文', verbose_name='评论内容')),
                ('like_count', models.IntegerField(default=0, help_text='该评论获得的点赞数量', verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='数据记录自动生成的时间戳', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论数据',
                'verbose_name_plural': '评论数据',
                'ordering': ['-comment_date'],
            },
        ),
        migrations.CreateModel(
            name='HotBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='热点在榜单中的位置', verbose_name='排名')),
                ('keyword', models.CharField(help_text='热点话题的核心关键词', max_length=255, verbose_name='关键词')),
                ('hot_value', models.IntegerField(help_text='衡量热点热度的数值指标', verbose_name='热度值')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='数据抓取时的系统时间', verbose_name='抓取时间')),
            ],
            options={
                'verbose_name': '热榜数据',
                'verbose_name_plural': '热榜数据',
                'ordering': ['-rank'],
            },
        ),
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_mai', models.CharField(max_length=100)),
                ('reg_pwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(help_text='视频的描述文案', verbose_name='视频文案')),
                ('video_date', models.DateTimeField(help_text='视频首次发布的时间', verbose_name='发布时间')),
                ('video_id', models.CharField(help_text='抖音系统分配的唯一视频标识符', max_length=255, unique=True, verbose_name='视频ID')),
                ('user_name', models.CharField(help_text='视频发布者的用户名', max_length=255, verbose_name='发布者')),
                ('collect_count', models.IntegerField(default=0, help_text='视频被收藏的次数', verbose_name='收藏数')),
                ('share_count', models.IntegerField(default=0, help_text='视频被转发的次数', verbose_name='转发数')),
                ('popularity', models.CharField(choices=[('热门', '热门'), ('正常', '正常')], default='正常', help_text='根据转发量定义的热度等级（热门/正常）', max_length=20, verbose_name='视频热度')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='数据记录自动生成的时间戳', verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '视频信息',
                'verbose_name_plural': '视频信息',
                'ordering': ['-video_date'],
            },
        ),
    ]
