# Generated by Django 4.2.18 on 2025-03-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='抖音的热搜关键词', max_length=255, unique=True, verbose_name='热搜关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='热搜关键词记录创建的时间戳', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '热搜关键词',
                'verbose_name_plural': '热搜关键词',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(help_text='该评论关联的视频', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.video', verbose_name='关联视频'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=255, verbose_name='用户昵称'),
        ),
        migrations.AddField(
            model_name='hotboard',
            name='hot_search',
            field=models.ForeignKey(blank=True, help_text='该热榜项关联的热搜关键词', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp01.hotsearch', verbose_name='关联热搜'),
        ),
        migrations.AddField(
            model_name='video',
            name='hot_search',
            field=models.ForeignKey(blank=True, help_text='该视频关联的热搜关键词', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp01.hotsearch', verbose_name='关联热搜'),
        ),
    ]
