# Generated by Django 4.2.18 on 2025-03-09 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp01', '0002_hotsearch_comment_video_alter_comment_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='用户昵称')),
                ('region', models.CharField(blank=True, help_text='用户所在地区（IP地址解析结果，可能为空）', max_length=255, null=True, verbose_name='用户地区')),
                ('comment_date', models.DateTimeField(help_text='评论发表的具体时间', verbose_name='评论时间')),
                ('content', models.TextField(help_text='用户发表的评论正文', verbose_name='评论内容')),
                ('like_count', models.IntegerField(default=0, help_text='该评论获得的点赞数量', verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='数据记录自动生成的时间戳', verbose_name='创建时间')),
                ('video', models.ForeignKey(help_text='该评论关联的视频', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.video', verbose_name='关联视频')),
            ],
            options={
                'verbose_name': '评论数据',
                'verbose_name_plural': '评论数据',
                'ordering': ['-comment_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='用户昵称')),
                ('region', models.CharField(blank=True, help_text='用户所在地区（IP地址解析结果，可能为空）', max_length=255, null=True, verbose_name='用户地区')),
                ('comment_date', models.DateTimeField(help_text='评论发表的具体时间', verbose_name='评论时间')),
                ('content', models.TextField(help_text='用户发表的评论正文', verbose_name='评论内容')),
                ('like_count', models.IntegerField(default=0, help_text='该评论获得的点赞数量', verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='数据记录自动生成的时间戳', verbose_name='创建时间')),
                ('video', models.ForeignKey(help_text='该评论关联的视频', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.video', verbose_name='关联视频')),
            ],
            options={
                'verbose_name': '评论数据',
                'verbose_name_plural': '评论数据',
                'ordering': ['-comment_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='用户昵称')),
                ('region', models.CharField(blank=True, help_text='用户所在地区（IP地址解析结果，可能为空）', max_length=255, null=True, verbose_name='用户地区')),
                ('comment_date', models.DateTimeField(help_text='评论发表的具体时间', verbose_name='评论时间')),
                ('content', models.TextField(help_text='用户发表的评论正文', verbose_name='评论内容')),
                ('like_count', models.IntegerField(default=0, help_text='该评论获得的点赞数量', verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='数据记录自动生成的时间戳', verbose_name='创建时间')),
                ('video', models.ForeignKey(help_text='该评论关联的视频', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.video', verbose_name='关联视频')),
            ],
            options={
                'verbose_name': '评论数据',
                'verbose_name_plural': '评论数据',
                'ordering': ['-comment_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='用户昵称')),
                ('region', models.CharField(blank=True, help_text='用户所在地区（IP地址解析结果，可能为空）', max_length=255, null=True, verbose_name='用户地区')),
                ('comment_date', models.DateTimeField(help_text='评论发表的具体时间', verbose_name='评论时间')),
                ('content', models.TextField(help_text='用户发表的评论正文', verbose_name='评论内容')),
                ('like_count', models.IntegerField(default=0, help_text='该评论获得的点赞数量', verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='数据记录自动生成的时间戳', verbose_name='创建时间')),
                ('video', models.ForeignKey(help_text='该评论关联的视频', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.video', verbose_name='关联视频')),
            ],
            options={
                'verbose_name': '评论数据',
                'verbose_name_plural': '评论数据',
                'ordering': ['-comment_date'],
            },
        ),
    ]
