# Generated by Django 4.2.18 on 2025-03-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp01', '0003_comment_5_comment_4_comment_3_comment_2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment_4',
            new_name='CommentHot1',
        ),
        migrations.RenameModel(
            old_name='Comment_5',
            new_name='CommentHot2',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentHot3',
        ),
        migrations.RenameModel(
            old_name='Comment_3',
            new_name='CommentHot4',
        ),
        migrations.RenameModel(
            old_name='Comment_2',
            new_name='CommentHot5',
        ),
        migrations.AlterModelOptions(
            name='commenthot1',
            options={'verbose_name': '热搜1评论数据', 'verbose_name_plural': '热搜1评论数据'},
        ),
        migrations.AlterModelOptions(
            name='commenthot2',
            options={'verbose_name': '热搜2评论数据', 'verbose_name_plural': '热搜2评论数据'},
        ),
        migrations.AlterModelOptions(
            name='commenthot3',
            options={'verbose_name': '热搜3评论数据', 'verbose_name_plural': '热搜3评论数据'},
        ),
        migrations.AlterModelOptions(
            name='commenthot4',
            options={'verbose_name': '热搜4评论数据', 'verbose_name_plural': '热搜4评论数据'},
        ),
        migrations.AlterModelOptions(
            name='commenthot5',
            options={'verbose_name': '热搜5评论数据', 'verbose_name_plural': '热搜5评论数据'},
        ),
    ]
