# Generated by Django 4.2.18 on 2025-03-11 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp01', '0004_rename_comment_4_commenthot1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenthot1',
            name='hot_board',
            field=models.ForeignKey(help_text='该评论关联的热搜', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.hotboard', verbose_name='关联热搜'),
        ),
        migrations.AddField(
            model_name='commenthot2',
            name='hot_board',
            field=models.ForeignKey(help_text='该评论关联的热搜', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.hotboard', verbose_name='关联热搜'),
        ),
        migrations.AddField(
            model_name='commenthot3',
            name='hot_board',
            field=models.ForeignKey(help_text='该评论关联的热搜', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.hotboard', verbose_name='关联热搜'),
        ),
        migrations.AddField(
            model_name='commenthot4',
            name='hot_board',
            field=models.ForeignKey(help_text='该评论关联的热搜', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.hotboard', verbose_name='关联热搜'),
        ),
        migrations.AddField(
            model_name='commenthot5',
            name='hot_board',
            field=models.ForeignKey(help_text='该评论关联的热搜', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.hotboard', verbose_name='关联热搜'),
        ),
    ]
