# Generated by Django 4.2.18 on 2025-03-13 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp01', '0005_commenthot1_hot_board_commenthot2_hot_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='reg_mai',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='reg_mail',
            field=models.CharField(default='active', help_text='用户注册时使用的邮箱', max_length=100, verbose_name='注册邮箱'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commenthot1',
            name='hot_board',
            field=models.ForeignKey(help_text='该评论关联的热榜', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.hotboard', verbose_name='关联热榜'),
        ),
        migrations.AlterField(
            model_name='commenthot2',
            name='hot_board',
            field=models.ForeignKey(help_text='该评论关联的热榜', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.hotboard', verbose_name='关联热榜'),
        ),
        migrations.AlterField(
            model_name='commenthot3',
            name='hot_board',
            field=models.ForeignKey(help_text='该评论关联的热榜', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.hotboard', verbose_name='关联热榜'),
        ),
        migrations.AlterField(
            model_name='commenthot4',
            name='hot_board',
            field=models.ForeignKey(help_text='该评论关联的热榜', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.hotboard', verbose_name='关联热榜'),
        ),
        migrations.AlterField(
            model_name='commenthot5',
            name='hot_board',
            field=models.ForeignKey(help_text='该评论关联的热榜', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp01.hotboard', verbose_name='关联热榜'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='reg_pwd',
            field=models.CharField(help_text='用户注册时设置的密码', max_length=100, verbose_name='注册密码'),
        ),
    ]
