# Generated by Django 4.2 on 2025-04-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp01', '0006_remove_registeruser_reg_mai_registeruser_reg_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenthot1',
            name='sentiment',
            field=models.CharField(max_length=10, null=True, verbose_name='情感分析结果'),
        ),
        migrations.AddField(
            model_name='commenthot2',
            name='sentiment',
            field=models.CharField(max_length=10, null=True, verbose_name='情感分析结果'),
        ),
        migrations.AddField(
            model_name='commenthot3',
            name='sentiment',
            field=models.CharField(max_length=10, null=True, verbose_name='情感分析结果'),
        ),
        migrations.AddField(
            model_name='commenthot4',
            name='sentiment',
            field=models.CharField(max_length=10, null=True, verbose_name='情感分析结果'),
        ),
        migrations.AddField(
            model_name='commenthot5',
            name='sentiment',
            field=models.CharField(max_length=10, null=True, verbose_name='情感分析结果'),
        ),
        migrations.AlterModelTable(
            name='commenthot1',
            table='CommentHot1',
        ),
        migrations.AlterModelTable(
            name='commenthot2',
            table='CommentHot2',
        ),
        migrations.AlterModelTable(
            name='commenthot3',
            table='CommentHot3',
        ),
        migrations.AlterModelTable(
            name='commenthot4',
            table='CommentHot4',
        ),
        migrations.AlterModelTable(
            name='commenthot5',
            table='CommentHot5',
        ),
    ]
