# Generated by Django 4.2 on 2026-03-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp01', '0007_commenthot1_sentiment_commenthot2_sentiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenthot1',
            name='comment_date',
            field=models.DateTimeField(db_index=True, help_text='评论发表的具体时间', verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='commenthot1',
            name='like_count',
            field=models.IntegerField(db_index=True, default=0, help_text='该评论获得的点赞数量', verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='commenthot2',
            name='comment_date',
            field=models.DateTimeField(db_index=True, help_text='评论发表的具体时间', verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='commenthot2',
            name='like_count',
            field=models.IntegerField(db_index=True, default=0, help_text='该评论获得的点赞数量', verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='commenthot3',
            name='comment_date',
            field=models.DateTimeField(db_index=True, help_text='评论发表的具体时间', verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='commenthot3',
            name='like_count',
            field=models.IntegerField(db_index=True, default=0, help_text='该评论获得的点赞数量', verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='commenthot4',
            name='comment_date',
            field=models.DateTimeField(db_index=True, help_text='评论发表的具体时间', verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='commenthot4',
            name='like_count',
            field=models.IntegerField(db_index=True, default=0, help_text='该评论获得的点赞数量', verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='commenthot5',
            name='comment_date',
            field=models.DateTimeField(db_index=True, help_text='评论发表的具体时间', verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='commenthot5',
            name='like_count',
            field=models.IntegerField(db_index=True, default=0, help_text='该评论获得的点赞数量', verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='hotboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='数据抓取时的系统时间', verbose_name='抓取时间'),
        ),
        migrations.AlterField(
            model_name='hotboard',
            name='rank',
            field=models.IntegerField(db_index=True, help_text='热点在榜单中的位置', verbose_name='排名'),
        ),
    ]
